# Generated by Django 3.1.2 on 2020-10-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0.25, max_digits=4),
        ),
    ]
